# -*- coding: utf-8 -*-
"""Assignment #1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WKs-bmfQzY5DGH1jG-Dl2HiDLtQitoNT
"""

#CS4650: Activity #1, Ocean Lu
import numpy as np

print("Part 1")
arr1d = np.arange(12)
print ("1d numpy array: ", arr1d)
arr2d = np.array([[1,2,3],[6,5,4]])
print ("2d numpy array: ", arr2d)

print("\nPart 2")
s = arr1d[4:7]
print("slice s:", s)
s[1] = 0
print ("After s[1] = 0:", s)
print ("arr1d:", arr1d)

print ("\nPart 3")
def factorial(n):
    number = 1
    for i in range(1,n+1):
        number = number * i
    return number

fact = np.vectorize(factorial)
print("vectorized computation: ", fact(arr2d))