# -*- coding: utf-8 -*-
"""Activity #3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xnjYu68DZU3DGQ88Rr_A7edoiP5xPO1w
"""

# Read your own datase
# file for CSV: https://catalog.data.gov/dataset/city-employee-salaries-march-2018

from google.colab import files
uploaded = files.upload()

# 1 line chart

import pandas as pd
import matplotlib.pyplot as plt

data = pd.read_csv('City_Employee_Salaries_March_2018.csv', index_col='Name')

data.plot.line()

# 1 bar chart

plt.bar(x=data['FID'],height=data['Annual_Rt'])

# 1 histogram

data.hist(bins=10)
plt.xlim([0,100])
plt.ylim([50,500])
plt.show()

# 1 pie chart

data.Annual_Rt.value_counts().head(10).plot.pie()
plt.gca().set_aspect('equal')

# 1 scatter graph

data.plot(x = 'FID', y = "Annual_Rt", kind = 'scatter')

# 1 either 3-D or map

import pandas as pd
from pandas import DataFrame
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

threedee = plt.figure().gca(projection='3d')
threedee.scatter(data.FID, data.Annual_Rt, data.Hrly_Rate)
threedee.set_xlabel('FID')
threedee.set_ylabel('Annual_Rt')
threedee.set_zlabel('Hrly_Rate')
plt.show()